apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: file-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-connect-cluster
spec:
  class: org.apache.kafka.connect.file.FileStreamSourceConnector
  tasksMax: 2
  config:
    file: "/opt/kafka/LICENSE"
    topic: sftp-file-testing-topic

