apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: sftp-csv-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-connect-cluster
spec:
  class: io.confluent.connect.sftp.SftpCsvSourceConnector
  tasksMax: 2
  config:
    behavior.on.error: IGNORE
    cleanup.policy: MOVE
    input.path: upload/csv/source
    error.path: upload/csv/error
    finished.path: upload/csv/output
    input.file.pattern: csv-sftp-source.csv
    sftp.username: foo
    sftp.password: password
    sftp.host: 52.187.164.6
    sftp.port: 2222
    kafka.topic: sftp-csv-testing-topic
    schema.generation.enabled: true
