apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  name: "postgres-connector"
  namespace: kafka
  labels:
    strimzi.io/cluster: my_connect_cluster
spec:
  class: "io.confluent.connect.jdbc.JdbcSourceConnector"
  tasksMax: 1
  config:
    connection.url: "jdbc:postgresql://ip_edge/player"
    connection.user: "postgres"
    connection.password: "mysecretpassword"
    table.whitelist: "football_players"
    mode: "timestamp"
    timestamp.column.name: "modified_at,created_at"
    poll.interval.ms: "2000"
    topic.prefix: "pg_source_"
